function toggleSVG() {
  var svg1 = document.getElementById('svg1');
  var circleSVG = '<svg width="24" height="24" viewBox="0 0 24 24" fill="#fff" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd"d="M2.99997 1.46732e-10H7.11997C7.91793 -7.88103e-06 8.68302 0.317892 9.24602 0.883388C9.80901 1.44888 10.1235 2.21538 10.12 3.01333V7.12C10.12 8.77685 8.77682 10.12 7.11997 10.12H2.99997C1.34311 10.12 -3.13633e-05 8.77685 -3.13633e-05 7.12V3.01333C-0.00357787 2.21538 0.310926 1.44888 0.87392 0.883388C1.43691 0.317892 2.202 -7.88103e-06 2.99997 1.46732e-10ZM7.11997 8.10667C7.66925 8.09949 8.11279 7.65595 8.11997 7.10667V3.01333C8.11997 2.46105 7.67225 2.01333 7.11997 2.01333H2.99997C2.44768 2.01333 1.99997 2.46105 1.99997 3.01333V7.10667C2.00715 7.65595 2.45069 8.09949 2.99997 8.10667H7.11997Z" fill="#FCFCFC" /> <path fill-rule="evenodd" clip-rule="evenodd"d="M16.88 1.46732e-10H21C21.798 -7.88103e-06 22.5631 0.317892 23.126 0.883388C23.689 1.44888 24.0035 2.21538 24 3.01333V7.12C24 8.77685 22.6569 10.12 21 10.12H16.88C15.2231 10.12 13.88 8.77685 13.88 7.12V3C13.88 1.34315 15.2231 1.46732e-10 16.88 1.46732e-10ZM21 8.10667C21.5493 8.09949 21.9928 7.65595 22 7.10667V3.01333C22 2.46105 21.5523 2.01333 21 2.01333H16.88C16.3277 2.01333 15.88 2.46105 15.88 3.01333V7.10667C15.8872 7.65595 16.3307 8.09949 16.88 8.10667H21Z" fill="#FCFCFC" /> <path fill-rule="evenodd" clip-rule="evenodd" d="M2.99997 13.88H7.11997C8.77682 13.88 10.12 15.2231 10.12 16.88V21C10.12 22.6569 8.77682 24 7.11997 24H2.99997C2.202 24 1.43691 23.6821 0.87392 23.1166C0.310926 22.5511 -0.00357787 21.7846 -3.13633e-05 20.9867V16.88C-3.13633e-05 15.2231 1.34311 13.88 2.99997 13.88ZM7.11997 21.9867C7.67225 21.9867 8.11997 21.539 8.11997 20.9867V16.88C8.11279 16.3307 7.66925 15.8872 7.11997 15.88H2.99997C2.45069 15.8872 2.00715 16.3307 1.99997 16.88V20.9867C1.99997 21.539 2.44768 21.9867 2.99997 21.9867H7.11997Z" fill="#FCFCFC" /> <path fill-rule="evenodd" clip-rule="evenodd" d="M16.88 13.88H21C22.6568 13.88 24 15.2231 24 16.88V20.9867C24.0035 21.7846 23.689 22.5511 23.126 23.1166C22.563 23.6821 21.7979 24 21 24H16.88C16.082 24 15.3169 23.6821 14.7539 23.1166C14.1909 22.5511 13.8764 21.7846 13.88 20.9867V16.88C13.88 15.2231 15.2231 13.88 16.88 13.88ZM21 21.9867C21.5523 21.9867 22 21.539 22 20.9867V16.88C21.9928 16.3307 21.5493 15.8872 21 15.88H16.88C16.3307 15.8872 15.8872 16.3307 15.88 16.88V20.9867C15.88 21.539 16.3277 21.9867 16.88 21.9867H21Z" fill="#FCFCFC" /></svg>';
  var anotherSVG = '<svg id="svg-x" width="24" height="24" viewBox="0 0 100 100"><line x1="10" y1="10" x2="90" y2="90" stroke="white" stroke-width="5" /><line x1="90" y1="10" x2="10" y2="90" stroke="white" stroke-width="5" /></svg>';

  if (svg1.getAttribute('data-clicked') === 'true') {
    // Return to original SVG
    svg1.innerHTML = circleSVG;
    svg1.removeAttribute('data-clicked');
  } else {
    // Change to another SVG
    svg1.innerHTML = anotherSVG;
    svg1.setAttribute('data-clicked', 'true');
  }
}

const select = document.querySelector(".select16");
const optionsList = document.querySelector(".options-list16");
const options = document.querySelectorAll(".options");

select.addEventListener("click", () => {
  optionsList.classList.toggle("options-visible");
  select.querySelector(".fa-angle-down").classList.toggle("fa-angle-up");
});

options.forEach((option) => {
  option.addEventListener("click", () => {
    options.forEach((option) => {
      option.classList.remove("selected");
    });
    select.querySelector("span").innerHTML = option.innerHTML;
    option.classList.add("selected");
    optionsList.classList.remove("options-visible");
    select.querySelector(".fa-angle-down").classList.remove("fa-angle-up");
  });
});

const buttons = document.querySelectorAll(".btn2");

const textElements = [
  "text",
  "text2",
  "text3",
  "text4",
  "text5",
  "text6",
  "text7",
  "text8",
  "text9",
  "text10",
  "text11",
  "text12",
  "text13",
  "text14",
  "text15",
  "text16",
  "text17",
  "text18",
  "text19",
  "text20",
  "text21",
  "text22",
  "text23",
  "text24",
  "text25",
  "text26",
  "text27",
  "text28",
  "text29",
  "text30",
  "text31",
  "text32",
  "text33",
  "text34",
  "text35",
  "text36",
  "text37",
  "text38",
  "text39",
  "text40",
  "text41",
  "text42",
  "text43",
  "text44",
  "text45",
  "text46",
  "text47",
  "text48",
  "text49",
  "text50",
  "text51",
  "text52",
  "text53",
  "text54",
  "text55",
  "text56",
  "text57",
  "text58",
  "text59",
  "text60",
  "text61",
  "text62",
  "text63",
  "text64",
  "text65",
  "text66",
  "text67",
  "text68",
  "text69",
  "text70",
  "text71",
  "text72",
  "text73",
  "text74",
  "text75",
  "text76",
  "text77",
  "text78",
  "text79",
  "text80",
  "text81",
  "text82",
  "text83",
  "text84",
  "text85",
  "text86",
  "text87",
  "text88",
  "text89",
  "text90",
  "text91",
  "text92",
  "text93",
  "text94",
  "text95",
  "text96",
  "text97",
  "text98",
  "text99",
  "text100",
  "text101",
  "text102",
  "text103",
  "text104",
  "text105",
  "text106",
  "text107",
  "text108",
  "text109",
  "text110",
  "text111",
  "text112",
  "text113",
  "text114",
  "text115",
  "text116",
  "text117",
  "text118",
  "text119",
  "text120",
  "text121",
  "text122",
  "text123",
  "text124",
  "text125",
  "text126",
  "text127",
  "text128",
  "text129",
  "text130",
  "text131",
  "text132",
  "text133",
  "text134",
  "text135",
  "text136",
  "text137",
  "text138",
  "text139",
  "text140",
  "text141",
  "text142",
  "text143",
  "text144",
  "text145",
  "text146",
  "text147",
  "text148",
  "text149",
  "text150",
  "text151",
  "text152",
  "text153",
  "text154",
  "text155",
  "text156",
  "text157",
  "text158",
  "text159",
  "till"
].map(id => document.getElementById(id));

buttons.forEach(button => {
  button.addEventListener("click", () => {
    const lang = button.getAttribute("lang");
    const translations = manba[lang];

    textElements.forEach((element, index) => {
      const key = element.id;
      if (translations[key] !== undefined) {
        element.textContent = translations[key];
      }
    });
  });
});

var manba = {
  rus: {
    text: "О курсе",
    text2: "О нас",
    text3: "Мнение читателей",
    text4: "Контакт",
    text5: "Стройте будущее вместе с NETPRO IT School",
    text6: "Запись на курс",
    text7: "Видео о курсе",
    text8: "Фронтенд разработчик",
    text9: "Это область создания веб-страницы и части веб-приложений, видимой пользователю.",
    text10: "Технологии",
    text11: "Оплата картой",
    text12: "UX UI дизайн",
    text13: "Удовлетворение потребностей пользователей в исследованиях и обратной связи помогает создавать интерфейсы.",
    text14: "Технологии",
    text15: "Оплата картой",
    text16: "Он обеспечивает передачу данных в ту часть веб-браузера, которую видит пользователь.",
    text17: "Технологии",
    text18: "Оплата картой",
    text19: "Компьютерная грамотность",
    text20: "Эффективное использование компьютерных и цифровых технологий, предоставление возможностей людям, обладающим навыками.",
    text21: "Технологии",
    text22: "Оплата картой",
    text23: "Проектируйте и разрабатывайте простую интерактивную игру с помощью Scratch.",
    text24: "Технологии",
    text25: "Оплата картой",
    text26: "Фронтенд разработчик",
    text27: "Это область создания веб-страницы и части веб-приложений, видимой пользователю.",
    text28: "Технологии",
    text29: "Оплата картой",
    text30: "UX UI дизайн",
    text31: "Удовлетворение потребностей пользователей в исследованиях и обратной связи помогает создавать интерфейсы.",
    text32: "Технологии",
    text33: "Оплата картой",
    text34: "Он обеспечивает передачу данных в ту часть веб-браузера, которую видит пользователь.",
    text35: "Технологии",
    text36: "Оплата картой",
    text37: "Компьютерная грамотность",
    text38: "Эффективное использование компьютерных и цифровых технологий, предоставление возможностей людям, обладающим навыками.",
    text39: "Технологии",
    text40: "Оплата картой",
    text41: "Проектируйте и разрабатывайте простую интерактивную игру с помощью Scratch.",
    text42: "Технологии",
    text43: "Оплата картой",
    text44: "Следующий шаг",
    text45: "После первого курса вы можете выбрать, где и как продолжить",
    text46: "Помощь в трудоустройстве",
    text47: "Наша цель заключается в том, чтобы мы активно помогали вам в трудоустройстве успешных выпускников учебного центра NetPro, которые достигли ваших целей в области образования и профессионального развития и показали хорошие результаты во время учебы.",
    text48: "Тип работы",
    text49: "Офисная работа",
    text50: "Заработная плата",
    text51: "От 2 000 000",
    text52: "До 7 000 000",
    text53: "Опыт работы",
    text54: "От 1 до 3 лет",
    text55: "Участие в стажировках",
    text56: "Практика-ключ к совершенствованию навыков и приобретению знаний. Активно участвуя, вы учитесь посредством повторения, экспериментов и обратной связи, а вместе с другими участниками реализуете идеи проектов и развиваете полученные знания на практике.",
    text57: "Тип работы",
    text58: "Офисная работа",
    text59: "Заработная плата",
    text60: "От 2 000 000",
    text61: "До 7 000 000",
    text62: "Опыт работы",
    text63: "От 1 до 3 лет",
    text64: "Коворкинг",
    text65: "Коворкинг-это офис, оборудованный всем необходимым, чтобы наши студенты могли дополнительно тренироваться и выполнять домашнее задание под наблюдением опытных администраторов.",
    text66: "Практика и выполнение домашних заданий",
    text67: "Поддержка и поддержка программы обучения",
    text68: "Советы ИТ-специалистов",
    text69: "Запись на курс",
    text70: "3d-модель",
    text71: "Город Ташкент",
    text72: "Мы ищем в нашей команде высококвалифицированного и опытного специалиста по 3D-моделированию. Идеальный кандидат должен хорошо разбираться в методах 3D-моделирования, программном обеспечении и передовых отраслевых методах.",
    text73: "Оставить ответ",
    text74: "Город Ташкент",
    text75: "Мы ищем в нашей команде высококвалифицированного и опытного специалиста по 3D-моделированию. Идеальный кандидат должен хорошо разбираться в методах 3D-моделирования, программном обеспечении и передовых отраслевых методах.",
    text76: "Оставить ответ",
    text77: "Город Ташкент",
    text78: "Мы ищем в нашей команде высококвалифицированного и опытного специалиста по 3D-моделированию. Идеальный кандидат должен хорошо разбираться в методах 3D-моделирования, программном обеспечении и передовых отраслевых методах.",
    text79: "Оставить ответ",
    text80: "Город Ташкент",
    text81: "Мы ищем в нашей команде высококвалифицированного и опытного специалиста по 3D-моделированию. Идеальный кандидат должен хорошо разбираться в методах 3D-моделирования, программном обеспечении и передовых отраслевых методах.",
    text82: "Оставить ответ",
    text83: "Город Ташкент",
    text84: "Мы ищем в нашей команде высококвалифицированного и опытного специалиста по 3D-моделированию. Идеальный кандидат должен хорошо разбираться в методах 3D-моделирования, программном обеспечении и передовых отраслевых методах.",
    text85: "Оставить ответ",
    text86: "Город Ташкент",
    text87: "Мы ищем в нашей команде высококвалифицированного и опытного специалиста по 3D-моделированию. Идеальный кандидат должен хорошо разбираться в методах 3D-моделирования, программном обеспечении и передовых отраслевых методах.",
    text88: "Оставить ответ",
    text89: "Город Ташкент",
    text90: "Мы ищем в нашей команде высококвалифицированного и опытного специалиста по 3D-моделированию. Идеальный кандидат должен хорошо разбираться в методах 3D-моделирования, программном обеспечении и передовых отраслевых методах.",
    text91: "Оставить ответ",
    text92: "Видео введение о курсе",
    text93: "Нажмите кнопку ниже, чтобы купить весь курс за единовременную оплату!",
    text94: "Запись на курс",
    text95: "Нажмите кнопку ниже, чтобы купить весь курс за единовременную оплату!",
    text96: "Запись на курс",
    text97: "Наши учителя",
    text98: "Шахло Джораева",
    text99: "Учитель по программированию",
    text100: "Тахир Ботиров",
    text101: "3D Макс инструктор",
    text102: "Аброр Абдуллаев",
    text103: "Учитель дизайна UX UI",
    text104: "Аброр Абдуллаев",
    text105: "Учитель дизайна UX UI",
    text106: "Шахло Джораева",
    text107: "Учитель по программированию",
    text108: "Тахир Ботиров",
    text109: "3D Макс инструктор",
    text110: "Как проводится обучение на платформе",
    text111: "Групповой чат",
    text112: "Для каждой мини-группы создается чат в Telegram, в котором учащиеся могут обсудить все учебные вопросы. Вы всегда можете получить быструю обратную связь от учителя или поговорить со своей группой.",
    text113: "Анализ домашнего задания",
    text114: "Для каждой мини-группы создается чат в Telegram, в котором учащиеся могут обсудить все учебные вопросы. Вы всегда можете получить быструю обратную связь от учителя или поговорить со своей группой.",
    text115: "Трудоустройство",
    text116: "Мы помогаем нашим ученикам в написании резюме, учителя готовы дать рекомендации. Мы работаем с крупнейшими базами данных о вакансиях и резюме ИТ - специалистов - Kwork и Upwork.",
    text117: "Сертификация",
    text118: "По окончании обучения вы получите сертификат и документ, в котором будет указано: - освоенный набор технологий; - средний балл за весь курс. - Количество решенных домашних заданий. - Окончательный проект.",
    text119: "Работа с куратором",
    text120: "Вы будете работать лично с одним преподавателем, профессиональным разработчиком, который поможет вам как в классе, так и при разборе домашних заданий и предоставлении комментариев.",
    text121: "Готовое портфолио",
    text122: "На каждом курсе студенты выполняют реальные проекты, которые можно добавить в свои портфолио, что очень помогает в поиске работы.",
    text123: "Часто задаваемые вопросы",
    text124: "Могу ли я стать программистом?",
    text125: "Заниматься разработкой может каждый. Курсы начинаются с основ, поэтому от вас не требуется никаких дополнительных знаний в области ИТ. Чтобы стать программистом, не нужно быть математиком или инженером и иметь какие-то особые идеи. Чтобы успешно пройти курс, нужно перестать сомневаться в себе, не лениться и выполнять все задания.",
    text126: "Что нужно для начала обучения?",
    text127: "Заниматься разработкой может каждый. Курсы начинаются с основ, поэтому от вас не требуется никаких дополнительных знаний в области ИТ. Чтобы стать программистом, не нужно быть математиком или инженером и иметь какие-то особые идеи. Чтобы успешно пройти курс, нужно перестать сомневаться в себе, не лениться и выполнять все задания.",
    text128: "Что я получу?",
    text129: "Заниматься разработкой может каждый. Курсы начинаются с основ, поэтому от вас не требуется никаких дополнительных знаний в области ИТ. Чтобы стать программистом, не нужно быть математиком или инженером и иметь какие-то особые идеи. Чтобы успешно пройти курс, нужно перестать сомневаться в себе, не лениться и выполнять все задания.",
    text130: "Нужен ли мне ноутбук?",
    text131: "Заниматься разработкой может каждый. Курсы начинаются с основ, поэтому от вас не требуется никаких дополнительных знаний в области ИТ. Чтобы стать программистом, не нужно быть математиком или инженером и иметь какие-то особые идеи. Чтобы успешно пройти курс, нужно перестать сомневаться в себе, не лениться и выполнять все задания.",
    text132: "Кто вас учит?",
    text133: "Заниматься разработкой может каждый. Курсы начинаются с основ, поэтому от вас не требуется никаких дополнительных знаний в области ИТ. Чтобы стать программистом, не нужно быть математиком или инженером и иметь какие-то особые идеи. Чтобы успешно пройти курс, нужно перестать сомневаться в себе, не лениться и выполнять все задания.",
    text134: "Наши курсы",
    text135: "3d макс",
    text136: "UX UI дизайн",
    text137: "Фронт-енд",
    text138: "Баск-енд",
    text139: "Компьютерная грамотность",
    text140: "Программирование скретч-игр",
    text141: "Разделы",
    text142: "О курсе",
    text143: "Мнение читателей",
    text144: "О нас",
    text145: "Контакт",
    text146: "Кратко о нас",
    text147: "NetPro-здесь начинается первый шаг в программировании!",
    text148: "Адрес:",
    text149: "Ташкент, Чиланзар, проспект Бунедкор",
  },
  eng: {
    text: "About the course",
    text2: "About us",
    text3: "Readers ' opinion",
    text4: "Contact",
    text5: "Create a future with Netpro it School",
    text6: "Enroll in the course",
    text7: "Video about the course",
    text8: "Frontend developer",
    text9: "This is the area of creating a web page and a part of web applications visible to the user.",
    text10: "Technologies",
    text11: "Payment by card",
    text12: "UX UI design",
    text13: "Meeting the needs of users for research and feedback helps to create interfaces.",
    text14: "Technologies",
    text15: "Payment by card",
    text16: "It provides data transfer to the part of the web browser that the user sees.",
    text17: "Technologies",
    text18: "Payment by card",
    text19: "Computer literacy",
    text20: "Effective use of computer and digital technologies, providing opportunities to people with skills.",
    text21: "Technologies",
    text22: "Payment by card",
    text23: "Design and develop a simple interactive game using Scratch.",
    text24: "Technologies",
    text25: "Payment by card",
    text26: "Frontend developer",
    text27: "This is the area of creating a web page and a part of web applications visible to the user.",
    text28: "Technologies",
    text29: "Payment by card",
    text30: "UX UI design",
    text31: "Meeting the needs of users for research and feedback helps to create interfaces.",
    text32: "Technologies",
    text33: "Payment by card",
    text34: "It provides data transfer to the part of the web browser that the user sees.",
    text35: "Technologies",
    text36: "Payment by card",
    text37: "Computer literacy",
    text38: "Effective use of computer and digital technologies, providing opportunities to people with skills.",
    text39: "Technologies",
    text40: "Payment by card",
    text41: "Design and develop a simple interactive game using Scratch.",
    text42: "Technologies",
    text43: "Payment by card",
    text44: "The next step",
    text45: "After the first course, you can choose where and how to continue",
    text46: "Employment assistance",
    text47: "Our goal is for us to actively help you find employment for successful graduates of the NetPro Training Center who have achieved your educational and professional development goals and have shown good results during their studies.",
    text48: "Type of work",
    text49: "Office work",
    text50: "Wages",
    text51: "From 2 000 000",
    text52: "Up to 7 000 000",
    text53: "Work experience",
    text54: "From 1 to 3 years old",
    text55: "Participation in internships",
    text56: "Practice is the key to improving skills and acquiring knowledge. By actively participating, you learn through repetition, experimentation and feedback, and together with other participants implement project ideas and develop the knowledge gained in practice.",
    text57: "Type of work",
    text58: "Office work",
    text59: "Wages",
    text60: "From 2 000 000",
    text61: "Up to 7 000 000",
    text62: "Work experience",
    text63: "From 1 to 3 years old",
    text64: "Coworking ",
    text65: "Coworking is an office equipped with everything necessary so that our students can additionally train and do their homework under the supervision of experienced administrators.",
    text66: "Practice and homework",
    text67: "Support and maintenance of the training program",
    text68: "Tips from IT specialists",
    text69: "Registration for the course",
    text70: "3d model",
    text71: "Toshkent city",
    text72: "We are looking for a highly qualified and experienced 3D modeling specialist in our team. The ideal candidate should be well versed in 3D modeling techniques, software, and industry best practices.",
    text73: "Leave a reply",
    text74: "Toshkent city",
    text75: "We are looking for a highly qualified and experienced 3D modeling specialist in our team. The ideal candidate should be well versed in 3D modeling techniques, software, and industry best practices.",
    text76: "Leave a reply",
    text74: "Toshkent city",
    text75: "We are looking for a highly qualified and experienced 3D modeling specialist in our team. The ideal candidate should be well versed in 3D modeling techniques, software, and industry best practices.",
    text76: "Leave a reply",
    text77: "Toshkent city",
    text78: "We are looking for a highly qualified and experienced 3D modeling specialist in our team. The ideal candidate should be well versed in 3D modeling techniques, software, and industry best practices.",
    text79: "Leave a reply",
    text80: "Toshkent city",
    text81: "We are looking for a highly qualified and experienced 3D modeling specialist in our team. The ideal candidate should be well versed in 3D modeling techniques, software, and industry best practices.",
    text82: "Leave a reply",
    text83: "Toshkent city",
    text84: "We are looking for a highly qualified and experienced 3D modeling specialist in our team. The ideal candidate should be well versed in 3D modeling techniques, software, and industry best practices.",
    text85: "Leave a reply",
    text86: "Toshkent city",
    text87: "We are looking for a highly qualified and experienced 3D modeling specialist in our team. The ideal candidate should be well versed in 3D modeling techniques, software, and industry best practices.",
    text88: "Leave a reply",
    text89: "Toshkent city",
    text90: "We are looking for a highly qualified and experienced 3D modeling specialist in our team. The ideal candidate should be well versed in 3D modeling techniques, software, and industry best practices.",
    text91: "Leave a reply",
    text92: "Video introduction about the course",
    text93: "Click the button below to buy the entire course for a one-time payment!",
    text94: "Registration for the course",
    text95: "Click the button below to buy the entire course for a one-time payment!",
    text96: "Registration for the course",
    text97: "Our teachers",
    text98: "Shakslo Joraeva",
    text99: "The programming teacher",
    text100: "Tahir Botirov",
    text101: "3D Max Instructor",
    text102: "Abror Abdullaev",
    text103: "UX UI Design Teacher",
    text104: "Abror Abdullaev",
    text105: "UX UI Design Teacher",
    text106: "Shakslo Joraeva",
    text107: "The programming teacher",
    text108: "Tahir Botirov",
    text109: "3D Max Instructor",
    text110: "How is training conducted on the platform",
    text111: "Group chat",
    text112: "A Telegram chat is created for each mini-group, in which students can discuss all educational issues. You can always get quick feedback from the teacher or talk to your group.",
    text113: "Homework analysis",
    text114: "A Telegram chat is created for each mini-group, in which students can discuss all educational issues. You can always get quick feedback from the teacher or talk to your group.",
    text115: "Employment",
    text116: "We help our students write resumes, and teachers are ready to give recommendations. We work with the largest databases of vacancies and resumes of IT specialists - Kwork and Upwork.",
    text117: "Certification",
    text118: "Upon completion of the training, you will receive a certificate and a document stating: - the mastered set of technologies; - the average score for the entire course. - The number of completed homework. - The final draft.",
    text119: "Working with a curator",
    text120: "You will work personally with one teacher, a professional developer who will help you both in the classroom and when analyzing homework and providing comments.",
    text121: "The finished portfolio",
    text122: "In each course, students complete real projects that can be added to their portfolios, which helps a lot in finding a job.",
    text123: "Frequently Asked Questions",
    text124: "Can I become a programmer?",
    text125: "Anyone can develop. The courses start with the basics, so no additional IT knowledge is required from you. To become a programmer, you don't need to be a mathematician or an engineer and have any special ideas. To successfully complete the course, you need to stop doubting yourself, not be lazy and complete all the tasks.",
    text126: "What do I need to start learning?",
    text127: "Anyone can develop. The courses start with the basics, so no additional IT knowledge is required from you. To become a programmer, you don't need to be a mathematician or an engineer and have any special ideas. To successfully complete the course, you need to stop doubting yourself, not be lazy and complete all the tasks.",
    text128: "What will I get?",
    text129: "Anyone can develop. The courses start with the basics, so no additional IT knowledge is required from you. To become a programmer, you don't need to be a mathematician or an engineer and have any special ideas. To successfully complete the course, you need to stop doubting yourself, not be lazy and complete all the tasks.",
    text130: "Do I need a laptop?",
    text131: "Anyone can develop. The courses start with the basics, so no additional IT knowledge is required from you. To become a programmer, you don't need to be a mathematician or an engineer and have any special ideas. To successfully complete the course, you need to stop doubting yourself, not be lazy and complete all the tasks.",
    text132: "Who teaches you?",
    text133: "Anyone can develop. The courses start with the basics, so no additional IT knowledge is required from you. To become a programmer, you don't need to be a mathematician or an engineer and have any special ideas. To successfully complete the course, you need to stop doubting yourself, not be lazy and complete all the tasks.",
    text134: "Our courses",
    text135: "3d max",
    text136: "UX UI design",
    text137: "Front-end",
    text138: "Back-end",
    text139: "Computer literacy",
    text140: "Scratch game programming",
    text141: "Sections",
    text142: "About the course",
    text143: "Readers' opinion",
    text144: "About us",
    text145: "Сontakt",
    text146: "Briefly about us",
    text147: "NetPro-this is where the first step in programming begins!",
    text148: "Address:",
    text149: "Tashkent, Chilanzar, Bunyodkor Avenue",
  },
  uz: {
    text: "Kurs haqida",
    text2: "Biz haqimizda",
    text3: "O’quvchilar fikri",
    text4: "Kontakt",
    text5: "NetPro IT School bilan kelajakni birga quring",
    text6: "Kursga yozilish",
    text7: "Kurs haqida video",
    text8: "Frontend dasturlash",
    text9: "Veb-sahifa va veb-ilovalarning foydalanuvchiga koʻrinadigan qismini hosil qilish sohasidir.",
    text10: "Texnologiyalar",
    text11: "Karta orqali to’lov",
    text12: "UX UI Dizayn",
    text13: "Tadqiqot va fikr-mulohazalarni foydalanuvchilar ehtiyojlarini qondirish interfeyslarni yaratishga yordam beradi.",
    text14: "Texnologiyalar",
    text15: "Karta orqali to’lov",
    text16: "Maʼlumotlarni veb-brauzerning foydalanuvchi koʻradigan qismiga qanday uzatilishini taʼminlaydi.",
    text17: "Texnologiyalar",
    text18: "Karta orqali to’lov",
    text19: "Kompyuter savodxonligi",
    text20: "Kompyuter va raqamli texnologiyalardan samarali foydalanish, ko'nikmalarga ega bo'lgan shaxslarga imkoniyat berish.",
    text21: "Texnologiyalar",
    text22: "Karta orqali to’lov",
    text23: "Scratch yordamida oddiy interaktiv o'yinni loyihalash va ishlab chiqish.",
    text24: "Texnologiyalar",
    text25: "Karta orqali to’lov",
    text26: "Frontend dasturlash",
    text27: "Veb-sahifa va veb-ilovalarning foydalanuvchiga koʻrinadigan qismini hosil qilish sohasidir.",
    text28: "Texnologiyalar",
    text29: "Karta orqali to’lov",
    text30: "UX UI Dizayn",
    text31: "Tadqiqot va fikr-mulohazalarni foydalanuvchilar ehtiyojlarini qondirish interfeyslarni yaratishga yordam beradi.",
    text32: "Texnologiyalar",
    text33: "Karta orqali to’lov",
    text34: "Maʼlumotlarni veb-brauzerning foydalanuvchi koʻradigan qismiga qanday uzatilishini taʼminlaydi.",
    text35: "Texnologiyalar",
    text36: "Karta orqali to’lov",
    text37: "Kompyuter savodxonligi",
    text38: "Kompyuter va raqamli texnologiyalardan samarali foydalanish, ko'nikmalarga ega bo'lgan shaxslarga imkoniyat berish.",
    text39: "Texnologiyalar",
    text40: "Karta orqali to’lov",
    text41: "Scratch yordamida oddiy interaktiv o'yinni loyihalash va ishlab chiqish.",
    text42: "Texnologiyalar",
    text43: "Karta orqali to’lov",
    text44: "Keyingi qadam",
    text45: "Birinchi kursdan so'ng siz qaerga va qanday davom etishni tanlashingiz mumkin",
    text46: "Bandlikga yordam berish",
    text47: "Bizning maqsadimiz sizga ta'lim va kasbiy rivojlanish maqsadlaringizni ro’yobga chiqaradigan va o’qish davomida yaxshi natijalar ko’rsatgan NetPro o’quv markazining muvaffaqiyatli bitiruvchilariga ishga joylashishda faol yordam beramiz.",
    text48: "Ish turi",
    text49: "Ofis ishi",
    text50: "Ish haqqi",
    text51: "2 000 000 dan",
    text52: "7 000 000 gacha",
    text53: "Ish tajribasi",
    text54: "1 yildan 3 yil gacha",
    text55: "Amaliyotlarda ishtirok etish",
    text56: "Amaliyot ko'nikmalarni takomillashtirish va bilim olishning kalitidir. Faol ishtirok etish orqali siz takrorlash, tajriba va  fikr-mulohazalar orqali o'rganasiz va boshqa ishtirokchilar bilan birgalikda siz loyihalar g'oyalarini amalga oshirasiz va olingan bilimlarni amalda ishlab chiqasiz.",
    text57: "Ish turi",
    text58: "Ofis ishi",
    text59: "Ish haqqi",
    text60: "2 000 000 dan",
    text61: "7 000 000 gacha",
    text62: "Ish tajribasi",
    text63: "1 yildan 3 yil gacha",
    text64: "Kovorking",
    text65: "Kovorking - bu talabalarmiz qo'shimcha ravishda mashg'ulishlari va tajribali ma'murlar nazorati ostida uy vazifalarini bajarishlari uchun zarur bo'lgan barcha narsalar bilan jihozlangan ofis.",
    text66: "Uy vazifasini mashq qilish va bajarish",
    text67: "O'qish dasturini qo'llab-quvvatlash va yordam",
    text68: "IT mutaxassislarining maslahatlari",
    text69: "Kursga yozilish",
    text70: "3d model",
    text71: "Toshkent shaxar",
    text72: "Biz jamoamizga yuqori malakali va tajribali 3D modellashtirish bo'yicha mutaxassisni qidirmoqdamiz. Ideal nomzod 3D modellashtirish texnikasi, dasturiy ta'minot va sanoatning eng yaxshi amaliyotlarini yaxshi bilishi kerak.",
    text73: "Javob qoldirish",
    text74: "Toshkent shaxar",
    text75: "Biz jamoamizga yuqori malakali va tajribali 3D modellashtirish bo'yicha mutaxassisni qidirmoqdamiz. Ideal nomzod 3D modellashtirish texnikasi, dasturiy ta'minot va sanoatning eng yaxshi amaliyotlarini yaxshi bilishi kerak.",
    text76: "Javob qoldirish",
    text74: "Toshkent shaxar",
    text75: "Biz jamoamizga yuqori malakali va tajribali 3D modellashtirish bo'yicha mutaxassisni qidirmoqdamiz. Ideal nomzod 3D modellashtirish texnikasi, dasturiy ta'minot va sanoatning eng yaxshi amaliyotlarini yaxshi bilishi kerak.",
    text76: "Javob qoldirish",
    text77: "Toshkent shaxar",
    text78: "Biz jamoamizga yuqori malakali va tajribali 3D modellashtirish bo'yicha mutaxassisni qidirmoqdamiz. Ideal nomzod 3D modellashtirish texnikasi, dasturiy ta'minot va sanoatning eng yaxshi amaliyotlarini yaxshi bilishi kerak.",
    text79: "Javob qoldirish",
    text80: "Toshkent shaxar",
    text81: "Biz jamoamizga yuqori malakali va tajribali 3D modellashtirish bo'yicha mutaxassisni qidirmoqdamiz. Ideal nomzod 3D modellashtirish texnikasi, dasturiy ta'minot va sanoatning eng yaxshi amaliyotlarini yaxshi bilishi kerak.",
    text82: "Javob qoldirish",
    text83: "Toshkent shaxar",
    text84: "Biz jamoamizga yuqori malakali va tajribali 3D modellashtirish bo'yicha mutaxassisni qidirmoqdamiz. Ideal nomzod 3D modellashtirish texnikasi, dasturiy ta'minot va sanoatning eng yaxshi amaliyotlarini yaxshi bilishi kerak.",
    text85: "Javob qoldirish",
    text86: "Toshkent shaxar",
    text87: "Biz jamoamizga yuqori malakali va tajribali 3D modellashtirish bo'yicha mutaxassisni qidirmoqdamiz. Ideal nomzod 3D modellashtirish texnikasi, dasturiy ta'minot va sanoatning eng yaxshi amaliyotlarini yaxshi bilishi kerak.",
    text88: "Javob qoldirish",
    text89: "Toshkent shaxar",
    text90: "Biz jamoamizga yuqori malakali va tajribali 3D modellashtirish bo'yicha mutaxassisni qidirmoqdamiz. Ideal nomzod 3D modellashtirish texnikasi, dasturiy ta'minot va sanoatning eng yaxshi amaliyotlarini yaxshi bilishi kerak.",
    text91: "Javob qoldirish",
    text92: "Kurs haqida video tanishtiruv",
    text93: " Bir marta to’lov qilib butun kursni sotib olish uchun quyidagi tugmani bosing!",
    text94: " Kursga yozilish",
    text95: "Bir marta to’lov qilib butun kursni sotib olish uchun quyidagi tugmani bosing!",
    text96: "Kursga yozilish",
    text97: "O'qutuvchilarimiz",
    text98: "Shaxlo Jo’raeva",
    text99: "Dasturlash o’qituvhcisi",
    text100: "Tohir Botirov",
    text101: "3d max o’qituvhcisi",
    text102: "Abror Abdullaev",
    text103: "UX UI dizayn o’qituvchisi",
    text104: "Abror Abdullaev",
    text105: "UX UI dizayn o’qituvchisi",
    text106: "Shaxlo Jo’raeva",
    text107: "Dasturlash o’qituvhcisi",
    text108: "Tohir Botirov",
    text109: "3d max o’qituvhcisi",
    text110: "Platformada o'qitish qanday amalga oshiriladi",
    text111: "Gurux suxbati",
    text112: "Har bir mini-guruh uchun Telegram-da suhbat yaratiladi, unda talabalar barcha o'quv masalalarini muhokama qilishlari mumkin. Siz har doim o'qituvchidan tezkor fikr-mulohazalarni olishingiz yoki guruhingiz bilan suhbatlashishingiz mumkin.",
    text113: "Uy vazifalarini  tahlil qilish",
    text114: "Har bir mini-guruh uchun Telegram-da suhbat yaratiladi, unda talabalar barcha o'quv masalalarini muhokama qilishlari mumkin. Siz har doim o'qituvchidan tezkor fikr-mulohazalarni olishingiz yoki guruhingiz bilan suhbatlashishingiz mumkin.",
    text115: "Ish bilan taminlash",
    text116: "Biz talabalarimizga rezyume yozishda yordam beramiz, o'qituvchilar tavsiyalar berishga tayyor. Biz it-mutaxassislarning eng yirik ish bazalari va rezyumelari-Kwork va Upwork bilan ishlaymiz.",
    text117: "Sertifikat",
    text118: "O'qishni tugatgandan so'ng siz sertifikat va hujjatni olasiz, unda quyidagilar ko'rsatiladi: - O'zlashtirilgan texnologiyalar to'plami; - Butun kurs uchun o'rtacha ball. - Hal qilingan uy vazifalari soni. - Yakuniy loyiha.",
    text119: "Kurator bilan ishlash",
    text120: "Siz bitta o'qituvchi, professional ishlab chiquvchi bilan shaxsan ishlaysiz, u sizga darsda ham, uy vazifangizni demontaj qilishda va sharhlar berishda ham yordam beradi.",
    text121: "Tayyor portfel",
    text122: "Har bir kursda talabalar o'z portfellariga qo'shilishi mumkin bo'lgan haqiqiy loyihalarni amalga oshiradilar, bu esa ish qidirishda katta yordam beradi.",
    text123: "Tez-tez so’raladigan savollar",
    text124: "Dasturchi bo’la olamanmi?",
    text125: "Har kim rivojlanish bilan shug'ullanishi mumkin. Kurslar asoslardan boshlanadi, shuning uchun sizdan IT sohasida qo'shimcha ma'lumot talab qilinmaydi. Dasturchi bo'lish uchun siz matematik yoki muhandis bo'lishingiz va biron bir maxsus fikrga ega bo'lishingiz shart emas. Kursni muvaffaqiyatli yakunlash uchun siz o'zingizga shubha qilishni to'xtatishingiz, dangasa bo'lmasligingiz va barcha vazifalarni bajarishingiz kerak.",
    text126: "Trening boshlash uchun nima kerak?",
    text127: "Har kim rivojlanish bilan shug'ullanishi mumkin. Kurslar asoslardan boshlanadi, shuning uchun sizdan IT sohasida qo'shimcha ma'lumot talab qilinmaydi. Dasturchi bo'lish uchun siz matematik yoki muhandis bo'lishingiz va biron bir maxsus fikrga ega bo'lishingiz shart emas. Kursni muvaffaqiyatli yakunlash uchun siz o'zingizga shubha qilishni to'xtatishingiz, dangasa bo'lmasligingiz va barcha vazifalarni bajarishingiz kerak.",
    text128: "Men nima olaman?",
    text129: "Har kim rivojlanish bilan shug'ullanishi mumkin. Kurslar asoslardan boshlanadi, shuning uchun sizdan IT sohasida qo'shimcha ma'lumot talab qilinmaydi. Dasturchi bo'lish uchun siz matematik yoki muhandis bo'lishingiz va biron bir maxsus fikrga ega bo'lishingiz shart emas. Kursni muvaffaqiyatli yakunlash uchun siz o'zingizga shubha qilishni to'xtatishingiz, dangasa bo'lmasligingiz va barcha vazifalarni bajarishingiz kerak.",
    text130: "Menga noutbook kerakmi?",
    text131: "Har kim rivojlanish bilan shug'ullanishi mumkin. Kurslar asoslardan boshlanadi, shuning uchun sizdan IT sohasida qo'shimcha ma'lumot talab qilinmaydi. Dasturchi bo'lish uchun siz matematik yoki muhandis bo'lishingiz va biron bir maxsus fikrga ega bo'lishingiz shart emas. Kursni muvaffaqiyatli yakunlash uchun siz o'zingizga shubha qilishni to'xtatishingiz, dangasa bo'lmasligingiz va barcha vazifalarni bajarishingiz kerak.",
    text132: "Sizga kim dars beradi?",
    text133: "Har kim rivojlanish bilan shug'ullanishi mumkin. Kurslar asoslardan boshlanadi, shuning uchun sizdan IT sohasida qo'shimcha ma'lumot talab qilinmaydi. Dasturchi bo'lish uchun siz matematik yoki muhandis bo'lishingiz va biron bir maxsus fikrga ega bo'lishingiz shart emas. Kursni muvaffaqiyatli yakunlash uchun siz o'zingizga shubha qilishni to'xtatishingiz, dangasa bo'lmasligingiz va barcha vazifalarni bajarishingiz kerak.",
    text134: "Kurslarimiz",
    text135: "3d max",
    text136: "UX UI dizayn",
    text137: "Front-end",
    text138: "Back-end",
    text139: "Kompyuter savodxonligi",
    text140: "Scratch o’yin dasturlash",
    text141: "Bo’limlar",
    text142: "Kurs haqida",
    text143: "O’quvchilar fikri",
    text144: "Biz haqimizda",
    text145: "Kontakt",
    text146: "Biz haqimizda qisqacha",
    text147: "NetPro-dasturlashga ilk qadam shu yerdan boshlanadi!",
    text148: "Manzil:",
    text149: " Toshkent, Chilonzor, Bunyodkor Shoh ko’chasi",
  }
};


$(".btn").click(function () {
  $(".option").toggle("show");
});
$(".btn-you").click(function () {
  $(".you").toggle("show");
});
$(".btn-we").click(function () {
  $(".we").toggle("show");
});
$(".btn-she").click(function () {
  $(".she").toggle("show");
});
$(".btn-they").click(function () {
  $(".they").toggle("show");
});
$(".btn-it").click(function () {
  $(".it").toggle("show");
});

var originalSizes = {
  box1: { height: 67 },
  box2: { height: 67 },
  box3: { height: 67 },
  box4: { height: 67 },
  box5: { height: 67 },
  box6: { height: 67 },
};

function toggleSize(id) {
  var box = document.getElementById(id);
  var currentWidth = box.offsetWidth;
  var currentHeight = box.offsetHeight;

  // Проверяем текущий размер
  if (
    currentHeight === originalSizes[id].height
  ) {
    // Увеличиваем размеры коробки
    box.style.height = "255px";
  } else {
    // Возвращаемся к первоначальному размеру
    box.style.height = originalSizes[id].height + "px";
  }
}
document.addEventListener("DOMContentLoaded", function () {
  const iconContainers = document.querySelectorAll(".dasturchi-box");

  iconContainers.forEach(function (iconContainer) {
    iconContainer.addEventListener("click", function () {
      this.classList.toggle("clicked"); // Переключение класса clicked
    });
  });
});
